spring.application.name=notesapi
spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.username=root
spring.datasource.password=agrim_dev_14

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.security.user.name=agrim
#spring.security.user.password=agrim_dev
#spring.security.user.roles=ADMIN
groq.api.key=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