spring.application.name=notesapi
spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.username=root
spring.datasource.password=agrim_dev_14

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.security.user.name=agrim
#spring.security.user.password=agrim_dev
#spring.security.user.roles=ADMIN